### ISSUE TITLE
🛑 Matrix is down

### ISSUE THREAD

**Issue by nya-cat** [nyaone/status#12]
In [`bcd688c`](https://github.com/nyaone/status/commit/bcd688c2ad181b3e6f3ed064736e916cd54f72df
), Matrix (https://nya.one/_matrix/client/versions) was **down**:
- HTTP code: 502
- Response time: 84 ms

**Comment by Candinya** [comment]
Synapse 新版 drop 了老 pg (<10) 的支持。
已经修复。
